default: &default
  adapter: postgresql
  url: postgresql://db:5432/
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres

development:
  <<: *default
  database: recipe_development

test:
  <<: *default
  database: recipe_test

production:
  <<: *default
  database: recipe_production
